### ISSUE TITLE
 I'm not logged in with the google API. 

### ISSUE THREAD

**Issue by hilalsaim** [UdacityAndroidDevScholarship/quiz-app#170]
Hi, I'm not logged in with the google API. I created the JKS file. I took the Sha1 code. I am trying to connect to my own FireBase, but not logging in

**Comment by hilalsaim** [comment]
I get an error like below;

D/WindowClient: Remove from mViews: DecorView@b828631[SignInHubActivity], this = android.view.WindowManagerGlobal@5bc4e7d
W/ViewRootImpl[SignInActivity]: Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=831, scanCode=470, metaState=META_FUNCTION_ON, flags=0x8, repeatCount=0, eventTime=237438048, downTime=237438048, deviceId=7, source=0x101 }
W/System.err: com.google.android.gms.common.api.ApiException: 10: 
W/System.err:     at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(Unknown Source)
W/System.err:     at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(Unknown Source)
W/System.err:     at com.developervishalsehgal.udacityscholarsapp.ui.signin.SignInActivity.onActivityResult(SignInActivity.java:122)
W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6954)
W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4194)
W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4241)
W/System.err:     at android.app.ActivityThread.-wrap20(ActivityThread.java)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1583)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
W/System.err:     at android.os.Looper.loop(Looper.java:208)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6267)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)``

**Comment by hilalsaim** [comment]
I solved the problem. I have not added WEB_CLIENT_ID
